// flow-typed signature: 2734dfa12171dd850472e59cf344b786
// flow-typed version: <<STUB>>/minihull_v2.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minihull'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minihull' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minihull/src/mini-hull' {
  declare module.exports: any;
}

declare module 'minihull/src/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minihull/src/mini-hull.js' {
  declare module.exports: $Exports<'minihull/src/mini-hull'>;
}
declare module 'minihull/src/router.js' {
  declare module.exports: $Exports<'minihull/src/router'>;
}
