// flow-typed signature: 7ba2b5b86ae76668d9ee204d3ac9fb65
// flow-typed version: <<STUB>>/mini-application_v^1.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mini-application'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mini-application' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mini-application/src/mini-application' {
  declare module.exports: any;
}

declare module 'mini-application/src/repl' {
  declare module.exports: any;
}

declare module 'mini-application/test/events-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/extend-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/http-error-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/incoming-request-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/interactive-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/outgoing-request-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/public-api-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/repl-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/reset-test' {
  declare module.exports: any;
}

declare module 'mini-application/test/stub-response-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mini-application/src/mini-application.js' {
  declare module.exports: $Exports<'mini-application/src/mini-application'>;
}
declare module 'mini-application/src/repl.js' {
  declare module.exports: $Exports<'mini-application/src/repl'>;
}
declare module 'mini-application/test/events-test.js' {
  declare module.exports: $Exports<'mini-application/test/events-test'>;
}
declare module 'mini-application/test/extend-test.js' {
  declare module.exports: $Exports<'mini-application/test/extend-test'>;
}
declare module 'mini-application/test/http-error-test.js' {
  declare module.exports: $Exports<'mini-application/test/http-error-test'>;
}
declare module 'mini-application/test/incoming-request-test.js' {
  declare module.exports: $Exports<'mini-application/test/incoming-request-test'>;
}
declare module 'mini-application/test/interactive-test.js' {
  declare module.exports: $Exports<'mini-application/test/interactive-test'>;
}
declare module 'mini-application/test/outgoing-request-test.js' {
  declare module.exports: $Exports<'mini-application/test/outgoing-request-test'>;
}
declare module 'mini-application/test/public-api-test.js' {
  declare module.exports: $Exports<'mini-application/test/public-api-test'>;
}
declare module 'mini-application/test/repl-test.js' {
  declare module.exports: $Exports<'mini-application/test/repl-test'>;
}
declare module 'mini-application/test/reset-test.js' {
  declare module.exports: $Exports<'mini-application/test/reset-test'>;
}
declare module 'mini-application/test/stub-response-test.js' {
  declare module.exports: $Exports<'mini-application/test/stub-response-test'>;
}
