// flow-typed signature: 10e35a2e6b2a24f4e87b72b5c76ffc5e
// flow-typed version: <<STUB>>/syntax-error_v^1.4.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'syntax-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'syntax-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'syntax-error/example/check' {
  declare module.exports: any;
}

declare module 'syntax-error/example/src' {
  declare module.exports: any;
}

declare module 'syntax-error/test/check' {
  declare module.exports: any;
}

declare module 'syntax-error/test/esm' {
  declare module.exports: any;
}

declare module 'syntax-error/test/html' {
  declare module.exports: any;
}

declare module 'syntax-error/test/ok' {
  declare module.exports: any;
}

declare module 'syntax-error/test/run' {
  declare module.exports: any;
}

declare module 'syntax-error/test/run2' {
  declare module.exports: any;
}

declare module 'syntax-error/test/shebang' {
  declare module.exports: any;
}

declare module 'syntax-error/test/sources/check' {
  declare module.exports: any;
}

declare module 'syntax-error/test/sources/esm' {
  declare module.exports: any;
}

declare module 'syntax-error/test/sources/ok' {
  declare module.exports: any;
}

declare module 'syntax-error/test/sources/run' {
  declare module.exports: any;
}

declare module 'syntax-error/test/sources/run2' {
  declare module.exports: any;
}

declare module 'syntax-error/test/sources/shebang' {
  declare module.exports: any;
}

declare module 'syntax-error/test/sources/spread' {
  declare module.exports: any;
}

declare module 'syntax-error/test/sources/yield' {
  declare module.exports: any;
}

declare module 'syntax-error/test/spread' {
  declare module.exports: any;
}

declare module 'syntax-error/test/yield' {
  declare module.exports: any;
}

// Filename aliases
declare module 'syntax-error/example/check.js' {
  declare module.exports: $Exports<'syntax-error/example/check'>;
}
declare module 'syntax-error/example/src.js' {
  declare module.exports: $Exports<'syntax-error/example/src'>;
}
declare module 'syntax-error/index' {
  declare module.exports: $Exports<'syntax-error'>;
}
declare module 'syntax-error/index.js' {
  declare module.exports: $Exports<'syntax-error'>;
}
declare module 'syntax-error/test/check.js' {
  declare module.exports: $Exports<'syntax-error/test/check'>;
}
declare module 'syntax-error/test/esm.js' {
  declare module.exports: $Exports<'syntax-error/test/esm'>;
}
declare module 'syntax-error/test/html.js' {
  declare module.exports: $Exports<'syntax-error/test/html'>;
}
declare module 'syntax-error/test/ok.js' {
  declare module.exports: $Exports<'syntax-error/test/ok'>;
}
declare module 'syntax-error/test/run.js' {
  declare module.exports: $Exports<'syntax-error/test/run'>;
}
declare module 'syntax-error/test/run2.js' {
  declare module.exports: $Exports<'syntax-error/test/run2'>;
}
declare module 'syntax-error/test/shebang.js' {
  declare module.exports: $Exports<'syntax-error/test/shebang'>;
}
declare module 'syntax-error/test/sources/check.js' {
  declare module.exports: $Exports<'syntax-error/test/sources/check'>;
}
declare module 'syntax-error/test/sources/esm.js' {
  declare module.exports: $Exports<'syntax-error/test/sources/esm'>;
}
declare module 'syntax-error/test/sources/ok.js' {
  declare module.exports: $Exports<'syntax-error/test/sources/ok'>;
}
declare module 'syntax-error/test/sources/run.js' {
  declare module.exports: $Exports<'syntax-error/test/sources/run'>;
}
declare module 'syntax-error/test/sources/run2.js' {
  declare module.exports: $Exports<'syntax-error/test/sources/run2'>;
}
declare module 'syntax-error/test/sources/shebang.js' {
  declare module.exports: $Exports<'syntax-error/test/sources/shebang'>;
}
declare module 'syntax-error/test/sources/spread.js' {
  declare module.exports: $Exports<'syntax-error/test/sources/spread'>;
}
declare module 'syntax-error/test/sources/yield.js' {
  declare module.exports: $Exports<'syntax-error/test/sources/yield'>;
}
declare module 'syntax-error/test/spread.js' {
  declare module.exports: $Exports<'syntax-error/test/spread'>;
}
declare module 'syntax-error/test/yield.js' {
  declare module.exports: $Exports<'syntax-error/test/yield'>;
}
